name = "my-worker"              # Worker 名称
main = "worker.js"             # Worker 类型
account_id = "b2e44eed415aae2b4017c796fe0064af" # Cloudflare 账户 ID
compatibility_date = "2025-10-26"

# 禁用 Wrangler 构建
[build]
command = ""
upload_format = "service-worker"
