name: Sync single file from upstream

on:
  schedule:
    - cron: "0 */6 * * *"  # 每 6 小时同步一次
  workflow_dispatch:       # 支持手动触发

jobs:
  sync-json:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout fork
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # 手动配置 token

      # 2️⃣ 配置远程仓库
      - name: Add upstream
        run: |
          git remote add upstream https://github.com/byJoey/cfnew.git
          git fetch upstream

      # 3️⃣ 获取上游默认分支
      - name: Determine upstream default branch
        id: branch
        run: |
          UPSTREAM_BRANCH=$(git remote show upstream | grep "HEAD branch" | cut -d ":" -f2 | tr -d ' ')
          echo "upstream_branch=$UPSTREAM_BRANCH" >> $GITHUB_OUTPUT

      # 4️⃣ 拉取单个文件并重命名
      - name: Fetch and rename file
        run: |
          mkdir tmp_upstream
          git --work-tree=tmp_upstream checkout upstream/${{ steps.branch.outputs.upstream_branch }} -- "少年你相信光吗"
          # 重命名为 URL 安全的名字
          cp tmp_upstream/少年你相信光吗 ./shaonian.json
          git add shaonian.json
          git commit -m "Update shaonian.json from upstream" || echo "No changes to commit"

      # 5️⃣ 配置 push 使用 PAT（避免 403）
      - name: Configure push with PAT
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/Jonney111/cf-vless.git

      # 6️⃣ Push 文件到 fork
      - name: Push changes
        run: git push origin ${{ steps.branch.outputs.upstream_branch }}
