name: Sync single file from upstream

on:
  schedule:
    - cron: "0 */6 * * *"  # 每 6 小时同步一次
  workflow_dispatch:       # 支持手动触发

jobs:
  sync-json:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout fork
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # 2️⃣ Add upstream and fetch
      - name: Add upstream
        run: |
          git remote add upstream https://github.com/byJoey/cfnew.git
          git fetch upstream

      # 3️⃣ Determine upstream default branch
      - name: Get upstream default branch
        id: branch
        run: |
          UPSTREAM_BRANCH=$(git remote show upstream | grep "HEAD branch" | cut -d ":" -f2 | tr -d ' ')
          echo "upstream_branch=$UPSTREAM_BRANCH" >> $GITHUB_OUTPUT

      # 4️⃣ Checkout fork default branch
      - name: Checkout fork branch
        run: |
          git checkout -B main  # 改成 master 如果你的 fork 默认分支是 master

      # 5️⃣ Configure Git user for commit
      - name: Configure Git user
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      # 6️⃣ List upstream files (debug)
      - name: List upstream files
        run: |
          git ls-tree -r upstream/${{ steps.branch.outputs.upstream_branch }}

      # 7️⃣ Attempt to fetch file (safe)
      - name: Fetch upstream file
        run: |
          mkdir -p tmp_upstream
          git --work-tree=tmp_upstream checkout upstream/${{ steps.branch.outputs.upstream_branch }} -- "少年你相信光吗" || echo "Upstream file not found"
          ls tmp_upstream

      # 8️⃣ Copy, rename, and commit if exists
      - name: Copy and commit file
        run: |
          if [ -f tmp_upstream/少年你相信光吗 ]; then
            cp tmp_upstream/少年你相信光吗 ./shaonian.json
            git add shaonian.json
            git commit -m "Update shaonian.json from upstream" || echo "No changes to commit"
          else
            echo "File not found, skipping commit"
          fi

      # 9️⃣ Configure push using PAT
      - name: Configure push with PAT
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/Jonney111/cf-vless.git

      # 🔟 Push changes
      - name: Push changes
        run: git push origin main
